project:
  type: website
  output-dir: docs
website:
  title: "lingkungan St.Andreas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - favorit.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

